Adiciona model de conta bancaria
NES-Collaborate/nes-website pull request #23
Opened 2024-02-27 21:36 UTC by ecaf1

coisa simples

2024-02-27 23:56 UTC, felipe-adeildo requested changes
Algumas coisas a serem consideradas:

1. Chegou a colocar essa nova coluna lá no notion? É preciso ter essa informaçõa lá para que algum momento possamos apresentar e entender pq essa tabela existe;
2. Sobre nomeclatura, vc usou `cont_type` e `cont_number` que eu acredio que sejam "tipo da conta" e "número da conta", sobre isso tenho duas coisas a falar:
- os termos corretos são `account_type` a `account_number`
- tem certeza que essas são todas as informações que queremos?
- o `account_type` seria o que? Se for algo pontual, pode ser um `Literal[...]` da vida ao invés de deixar aberto.

Considerando essas informações, corrija a nomeclatura e adicione no notion novamente.

2024-02-28 13:10 UTC, ecaf1 commented
Correções feitas

2024-02-28 13:47 UTC, ecaf1 commented
Tem sim no notion Kreley de disse que teria que ser cadastrado dados para
pagamento de bolsa, entretanto ele não definiu o que exatamente ele queria,
fiz pesquisa rápida e todas as informações necessárias para realizar
transferência do tipo TED mais o famoso pix, irei confirmar com ele hoje.
Realizei  a correção no nome dos atributos e segui sugestão de colocar
account_type como literal.

Em ter., 27 de fev. de 2024 às 23:56, Felipe Adeildo <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> Algumas coisas a serem consideradas:
>
>    1. Chegou a colocar essa nova coluna lá no notion? É preciso ter essa
>    informaçõa lá para que algum momento possamos apresentar e entender pq essa
>    tabela existe;
>    2. Sobre nomeclatura, vc usou cont_type e cont_number que eu acredio
>    que sejam "tipo da conta" e "número da conta", sobre isso tenho duas coisas
>    a falar:
>
>
>    - os termos corretos são account_type a account_number
>    - tem certeza que essas são todas as informações que queremos?
>    - o account_type seria o que? Se for algo pontual, pode ser um
>    Literal[...] da vida ao invés de deixar aberto.
>
> Considerando essas informações, corrija a nomeclatura e adicione no notion
> novamente.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NES-Collaborate/nes-website/pull/23#pullrequestreview-1905034519>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXOE5RUOFCB7F7SC7QXLODYVZXETAVCNFSM6AAAAABD436DI6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMBVGAZTINJRHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-28 17:31 UTC, felipe-adeildo approved these changes

2024-02-28 17:32 UTC, merged