Modifica layout das notícias e casos de sucesso
NES-Collaborate/nes-website pull request #40
Opened 2024-04-13 14:57 UTC by AmonVanderlei

Obs.: Não adicionei o scroll horizontal nos casos de sucesso, pois como há uma página dedicada somente à eles, acredito que não faça sentido a página ter somente esse scroll horizontal.

2024-04-13 16:02 UTC, felipe-adeildo commented
fixes #37

2024-04-15 23:43 UTC, AmonVanderlei commented
fixes #38

2024-04-27 13:29 UTC, felipe-adeildo requested changes
Assim como discutido em reunião.

2024-05-11 13:55 UTC, felipeadeildo approved these changes

2024-05-11 13:56 UTC, merged